version: '1.0.0.{build}.{branch}'

init:
 - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

before_build: 
 - appveyor-retry dotnet restore -v Minimal
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json

test_script:
 - dotnet build